steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args: [
      "build",
      "-t", "gcr.io/$PROJECT_ID/projek-kos-backend",
      "."
    ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/projek-kos-backend"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "projek-kos-backend",                # ← nama service Cloud Run
      "--image", "gcr.io/$PROJECT_ID/projek-kos-backend",  # ← nama Docker image
      "--timeout", "1000s",
      "--port", "5000",
      "--region", "us-central1",
      "--allow-unauthenticated"
    ]

options:
  logging: CLOUD_LOGGING_ONLY
